create table soldes (
  id SERIAL,
  idUser int,
  idWallet int,
  idTransaction int,
  idAsset int,
  crypto varchar,
  cryptoid varchar,
  soldeAchat numeric,
  valeurAchat numeric,
  soldeVente numeric,
  valeurVente numeric,
  avgBuyPrice numeric,
  avgSellPrice numeric,
  solde numeric,
  dateff timestamp default current_timestamp,
  datfin timestamp );